version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Changed YOUR_REGION to us-east-1
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 675266034256.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_NAME=rag-api
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_NAME .
      - docker tag $REPOSITORY_NAME:latest 675266034256.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY_NAME:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      # Fixed the URL to start with your Account ID
      - docker push 675266034256.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY_NAME:latest
artifacts:
  files:
    - '**/*'
